#!/bin/bash
##################################################################################
# Modo de uso:                                                                   #
# Copiar este archivo a /usr/local/bin, darle permisos de ejecución (chmod +x) y #
# ejecutar el comando `build` desde la consola para compilar todos los procesos, #
# o `build {proceso}` para compilar algún proceso en particular.                 #
##################################################################################
base="/home/utnso/git/tp-2017-2c-YATPOS"
declare -A procs=([dnode]="DataNode" [fs]="FileSystem" [master]="Master" [worker]="Worker" [yama]="YAMA")
[[ "$#" -eq 1 && ("$1" == "node" || -n "${procs[$1]}") ]] && proc="$1" || proc="all"
[ -n "${procs[$proc]}" ] && n=1 || n=0

printf "Building module%.*s…\n" $((n != 1)) "s"

for kcur in "${!procs[@]}"; do
	[[ "$proc" != "all" ]] && [[ "$kcur" != "$proc" ]] && [[ "$proc" != "node" || "$kcur" != "dnode" && "$kcur" != "worker" ]] && continue
	vcur="${procs[$kcur]}"
	echo -n " • $vcur: building…"
	make all -s -B -C $base/$vcur/Debug &> /dev/null
	echo -e "\r\e[0K • $vcur: done."
done
