#!/bin/bash
##################################################################################
# Modo de uso:                                                                   #
# Copiar este archivo a /usr/local/bin, darle permisos de ejecución (chmod +x) y #
# ejecutar el comando `build` desde la consola para compilar todos los procesos. #
##################################################################################
base="/home/utnso/git/tp-2017-2c-YATPOS"
cwd=$(pwd)
procs=("DataNode" "FileSystem" "Master" "Worker" "YAMA")
for proc in "${procs[@]}"; do
	dir="$base/$proc/Debug"
	if [ -d "$dir" ]; then
		cd $dir
		echo -e "\033[1;33m[$proc]\033[0m"
		make all
	fi
done
cd $cwd
