#!/bin/bash
##################################################################################
# Modo de uso:                                                                   #
# Copiar este archivo a /usr/local/bin, darle permisos de ejecución (chmod +x) y #
# ejecutar el comando `config` desde la consola para configurar todos los        #
# procesos, o `config {proceso}` para configurar algún proceso en particular.    #
##################################################################################
base="/home/utnso/git/tp-2017-2c-YATPOS"
yatpos="/home/utnso/yatpos"
declare -A procs=([node]="Node" [fs]="FileSystem" [master]="Master" [yama]="YAMA")

if [[ "$#" -eq 0 || ("$#" -eq 1 && "$1" == "all") ]]; then
	curs=("fs" "yama" "master" "node")
else
	for p in "$@"; do
		if [[ ! " ${!procs[@]} " =~ " $p " ]]; then
			echo "Usage: config [node|fs|master|yama|all]"
			exit
		fi
	done
	curs=("$@")
fi

mkdir -p $yatpos/config

for kcur in "${curs[@]}"; do
	vcur="${procs[$kcur]}"
	file="$yatpos/config/$vcur.cnf"
	[ ! -f $file ] && cp $base/Shared/rsc/config/$vcur.cnf $file
	echo -e "\e[1m$vcur.cnf\e[0m:"
	IFS="="
	while read -r name value; do
		echo -n " • $name (${value//\"/}) = "
		read new_value < /dev/tty
		if [[ ! -z "$new_value" ]]; then
			if [[ "$name" =~ "SIZE" ]]; then
				new_value=$(echo "$new_value" | awk '/[0-9]$/{print $1;next};/[mM]$/{printf "%u\n", $1*(1024*1024);next};/[kK]$/{printf "%u\n", $1*1024;next}')
			elif [[ "$name" =~ "IP" && ! "$new_value" =~ "." ]]; then
				new_value="192.168.3.$new_value"
			fi
			sed -i "s/^\($name=\).*/\1$new_value/" $file
		fi
	done < $file
done
