#!/bin/bash
##################################################################################
# Modo de uso:                                                                   #
# Copiar este archivo a /usr/local/bin, darle permisos de ejecución (chmod +x) y #
# ejecutar el comando `log {proceso}` desde la consola para ver el log de un     #
# proceso. [proceso puede ser dnode, fs, master, worker o yama]                  #
##################################################################################
logdir="/home/utnso/yatpos/logs"
declare -A procs=([dnode]="DataNode" [fs]="FileSystem" [master]="Master" [worker]="Worker" [yama]="YAMA")
if [ "$#" -ne 1 ] || ! [[ " ${!procs[@]} " =~ " $1 " ]] && ! [[ " node all " =~ " $1 " ]]; then
	echo "Uso: log [dnode|fs|master|worker|yama|node|all]"
	exit
fi
mkdir -p $logdir && cd $logdir
if [[ "$1" == "node" ]]; then
	logfiles="DataNode.log Worker.log"
elif [[ "$1" == "all" ]]; then
	logfiles=$(printf "%s.log " "${procs[@]}")
else
	logfiles="${procs[$1]}.log"
fi
touch $logfiles && tail -qF $logfiles
cd - &> /dev/null
