#!/bin/bash
##################################################################################
# Modo de uso:                                                                   #
# Copiar este archivo a /usr/local/bin, darle permisos de ejecución (chmod +x) y #
# ejecutar el comando `log {proceso}` desde la consola para ver el log de un     #
# proceso. [proceso puede ser dnode, fs, master, worker o yama]                  #
##################################################################################
logdir="/home/utnso/yatpos/logs"
declare -A procs=([dnode]="DataNode" [fs]="FileSystem" [master]="Master" [worker]="Worker" [yama]="YAMA")
#[ "$#" -lt 1 ] && proc="all" || proc="$1"

if [[ "$#" -eq 0 || ("$#" -eq 1 && "$1" == "all") ]]; then
	curs=("fs" "dnode" "yama" "worker" "master")
else
	for p in "$@"; do
		if [[ "$p" != "node" && ! -n "${procs[$p]}" ]]; then
			echo "Usage: build [dnode|fs|master|worker|yama|node|all]"
			exit
		fi
	done
	curs=($(echo "$@" | sed 's/\bnode\b/dnode worker/g'))
fi

for ((i=0; i<${#curs[@]}; i++)); do
	cur="${curs[$i]}"
	curs[$i]="${procs[$cur]}.log"
done

mkdir -p $logdir && cd $logdir
logfiles=$(printf "%s " "${curs[@]}")
touch $logfiles
printf "\033c"
tail -qF $logfiles
cd - &> /dev/null
