#!/bin/bash
base="/home/utnso/git/tp-2017-2c-YATPOS/Shared/scripts"
if [[ "$#" -ne 1 && "$#" -ne 2 || ! -f "$base/$1" ]]; then
	echo "Usage: yatpos [build|config|log|uninstall]"
	exit
fi
[[ "$#" -eq 2 ]] && "$base/$1" "$2" || "$base/$1"
