#!/bin/bash
base="/home/utnso/git/tp-2017-2c-YATPOS/Shared/scripts"
if [[ "$#" -lt 1 || ! -f "$base/$1" ]]; then
	echo "Usage: yatpos [get|build|config|run|log|uninstall]"
	exit
fi
"$base/$1" "${@:2}"
